<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="49" started-at="2017-05-18T06:01:43Z" finished-at="2017-05-18T06:01:43Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="49" started-at="2017-05-18T06:01:43Z" finished-at="2017-05-18T06:01:43Z">
      <class name="com.web.automation.JIRATestResult">
        <test-method status="PASS" signature="testmethod1()[pri:0, instance:com.web.automation.JIRATestResult@17ea32c]" name="testmethod1" duration-ms="15" started-at="2017-05-18T02:01:43Z" finished-at="2017-05-18T02:01:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testmethod1 -->
        <test-method status="PASS" signature="testmethod2()[pri:0, instance:com.web.automation.JIRATestResult@17ea32c]" name="testmethod2" duration-ms="4" started-at="2017-05-18T02:01:43Z" finished-at="2017-05-18T02:01:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testmethod2 -->
        <test-method status="FAIL" signature="testmethod3()[pri:0, instance:com.web.automation.JIRATestResult@17ea32c]" name="testmethod3" duration-ms="7" started-at="2017-05-18T02:01:43Z" finished-at="2017-05-18T02:01:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [QTP] but found [Selenium]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [QTP] but found [Selenium]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.web.automation.JIRATestResult.testmethod3(JIRATestResult.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testmethod3 -->
      </class> <!-- com.web.automation.JIRATestResult -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
